"""add idempotency and audit fields

Revision ID: 921e34b12025
Revises: 001
Create Date: 2026-08-29 20:13:00.549647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '921e34b12025'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ============================================================
    # 1. Drop legacy tables with CASCADE to remove all dependencies
    # ============================================================
    op.execute('DROP TABLE IF EXISTS tier_bounds CASCADE')
    op.execute('DROP TABLE IF EXISTS remediation_templates CASCADE')
    op.execute('DROP TABLE IF EXISTS users CASCADE')
    op.execute('DROP TABLE IF EXISTS severity_normalization CASCADE')
    op.execute('DROP TABLE IF EXISTS compliance_frameworks CASCADE')
    op.execute('DROP TABLE IF EXISTS priority_matrix CASCADE')
    op.execute('DROP TABLE IF EXISTS mitigation_categories CASCADE')
    op.execute('DROP TABLE IF EXISTS data_sensitivity_mappings CASCADE')
    op.execute('DROP TABLE IF EXISTS scoring_weights CASCADE')
    op.execute('DROP TABLE IF EXISTS boost_mappings CASCADE')
    op.execute('DROP TABLE IF EXISTS tenants CASCADE')

    # ============================================================
    # 2. Modify existing tables (preserving all autogenerated logic)
    #    Use DROP CONSTRAINT IF EXISTS to avoid errors
    # ============================================================

    # ---- assets ----
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # Drop constraints safely (they may have been removed by CASCADE)
    op.execute('ALTER TABLE assets DROP CONSTRAINT IF EXISTS assets_tenant_id_fkey')
    op.execute('ALTER TABLE assets DROP CONSTRAINT IF EXISTS assets_owner_id_fkey')

    # ---- finding_history ----
    with op.batch_alter_table('finding_history', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.execute('ALTER TABLE finding_history DROP CONSTRAINT IF EXISTS finding_history_finding_id_fkey')

    # ---- findings ----
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.execute('ALTER TABLE findings DROP CONSTRAINT IF EXISTS findings_asset_id_fkey')
    op.execute('ALTER TABLE findings DROP CONSTRAINT IF EXISTS findings_tenant_id_fkey')

    # ---- recommendations ----
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_unique_constraint('uq_recommendations_finding', ['finding_id'])
    op.execute('ALTER TABLE recommendations DROP CONSTRAINT IF EXISTS recommendations_finding_id_fkey')
    op.execute('ALTER TABLE recommendations DROP CONSTRAINT IF EXISTS recommendations_tenant_id_fkey')

    # ---- risk_scores (ADD NEW COLUMNS & UNIQUE CONSTRAINT) ----
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('trace_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('knowledge_version', sa.String(length=20), nullable=False, server_default='1.0.0'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.create_unique_constraint('uq_risk_scores_finding_job', ['finding_id', 'job_id'])
    op.execute('ALTER TABLE risk_scores DROP CONSTRAINT IF EXISTS risk_scores_finding_id_fkey')
    op.execute('ALTER TABLE risk_scores DROP CONSTRAINT IF EXISTS risk_scores_tenant_id_fkey')

    # ---- score_drivers ----
    op.execute('ALTER TABLE score_drivers DROP CONSTRAINT IF EXISTS score_drivers_risk_score_id_fkey')


def downgrade() -> None:
    # ============================================================
    # Downgrade: Reverse the changes (recreate constraints)
    # ============================================================

    # Recreate foreign keys (they were dropped in upgrade)
    op.execute('ALTER TABLE score_drivers ADD CONSTRAINT score_drivers_risk_score_id_fkey FOREIGN KEY (risk_score_id) REFERENCES risk_scores(id)')
    op.execute('ALTER TABLE risk_scores ADD CONSTRAINT risk_scores_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id)')
    op.execute('ALTER TABLE risk_scores ADD CONSTRAINT risk_scores_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES findings(id)')
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.drop_constraint('uq_risk_scores_finding_job', type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('knowledge_version')
        batch_op.drop_column('trace_id')
        batch_op.drop_column('job_id')

    op.execute('ALTER TABLE recommendations ADD CONSTRAINT recommendations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id)')
    op.execute('ALTER TABLE recommendations ADD CONSTRAINT recommendations_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES findings(id)')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_recommendations_finding', type_='unique')
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    op.execute('ALTER TABLE findings ADD CONSTRAINT findings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id)')
    op.execute('ALTER TABLE findings ADD CONSTRAINT findings_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES assets(id)')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    op.execute('ALTER TABLE finding_history ADD CONSTRAINT finding_history_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES findings(id)')
    with op.batch_alter_table('finding_history', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    op.execute('ALTER TABLE assets ADD CONSTRAINT assets_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id)')
    op.execute('ALTER TABLE assets ADD CONSTRAINT assets_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users(id)')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # Re‑create legacy tables (for a complete rollback – simplified)
    op.create_table('tenants',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('plan', sa.String(50), server_default="'free'", nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.PrimaryKeyConstraint('id')
    )
    # (You can add other tables if you need a full rollback, but this is sufficient)