"""Recommendation entity representing remediation guidance."""

from dataclasses import dataclass
from typing import Optional
from uuid import UUID

from src.core.exceptions.domain import ValidationError


@dataclass(frozen=True)
class Recommendation:
    """Recommendation entity representing remediation guidance.

    Attributes:
        id: Unique recommendation identifier.
        finding_id: The finding this recommendation applies to.
        tenant_id: Tenant identifier.
        technical_text: Technical remediation steps.
        business_explanation: Business-focused explanation (AI-generated).
        estimated_effort: Estimated effort to fix (low/medium/high).
        estimated_impact: Estimated impact score (0-100).
        risk_reduction_potential: Potential BIS reduction after remediation.
        priority: Priority tier (based on finding).
        category: Finding category for template matching.
        created_at: Creation timestamp.
        updated_at: Last update timestamp.
    """

    id: UUID
    finding_id: UUID
    tenant_id: UUID
    technical_text: str
    business_explanation: Optional[str]
    estimated_effort: str
    estimated_impact: int
    risk_reduction_potential: float
    priority: str
    category: str
    created_at: int
    updated_at: int

    def __post_init__(self) -> None:
        """Validate recommendation invariants."""
        if not self.technical_text:
            raise ValidationError("Technical text cannot be empty", field="technical_text")
        if not 0 <= self.estimated_impact <= 100:
            raise ValidationError(
                f"Estimated impact must be between 0 and 100, got {self.estimated_impact}",
                field="estimated_impact",
                value=self.estimated_impact,
            )
        if self.risk_reduction_potential < 0 or self.risk_reduction_potential > 100:
            raise ValidationError(
                f"Risk reduction potential must be between 0 and 100, got {self.risk_reduction_potential}",
                field="risk_reduction_potential",
                value=self.risk_reduction_potential,
            )

    @property
    def has_business_explanation(self) -> bool:
        """Check if a business explanation is available."""
        return self.business_explanation is not None and self.business_explanation.strip() != ""

    @property
    def is_high_impact(self) -> bool:
        """Check if the estimated impact is high (> 75)."""
        return self.estimated_impact >= 75

    @classmethod
    def create(
        cls,
        finding_id: UUID,
        tenant_id: UUID,
        technical_text: str,
        estimated_effort: str,
        estimated_impact: int,
        risk_reduction_potential: float,
        priority: str,
        category: str,
        business_explanation: Optional[str] = None,
    ) -> "Recommendation":
        """Factory method to create a recommendation.

        Args:
            finding_id: Finding identifier.
            tenant_id: Tenant identifier.
            technical_text: Technical remediation steps.
            estimated_effort: Estimated effort.
            estimated_impact: Estimated impact score.
            risk_reduction_potential: Potential BIS reduction.
            priority: Priority tier.
            category: Finding category.
            business_explanation: Optional AI-generated explanation.

        Returns:
            Recommendation: New recommendation instance.
        """
        now = int(__import__("time").time())
        return cls(
            id=UUID(int=0),  # Will be generated by repository
            finding_id=finding_id,
            tenant_id=tenant_id,
            technical_text=technical_text,
            business_explanation=business_explanation,
            estimated_effort=estimated_effort,
            estimated_impact=estimated_impact,
            risk_reduction_potential=risk_reduction_potential,
            priority=priority,
            category=category,
            created_at=now,
            updated_at=now,
        )